### ISSUE TITLE
Opening the Fleet Manager window crashes UE5.1

### ISSUE THREAD

**Issue by Herbie43** [spayne/GameLiftStarterPlugin#1]
[FleetManagerLog.txt]
I noticed that it defaults to your profile name. In another project I've encountered this same issue with my aws details.

**Comment by spayne** [comment]
It's probably the escaping of paths - e.g. the space in "C:/Users/PC/Documents/Unreal Projects/ThirdPersonGamelift/"  I'll try and repro the issue and confirm.
Thanks

**Comment by spayne** [comment]
Hi Herb,

I was able to reproduce the problem you found when I tested a server package root with spaces (ie E:\unreal folder with space\MyProject5\Packaged\WindowsServer).  So I needed to add some calls to [URLEncode](https://github.com/spayne/GameLiftStarterPlugin/blob/975a911fe4fce24a7a1682c126d01a68aa341f9e/Source/FleeteratorGameLiftStarterEditor/Private/FleeteratorGameLiftStarterEditor.cpp#L37) it 

You noticed that it was defaulting to my profile name - so I also tested the case where an invalid AWSProfile was used and made sure that you get a warning about that.

So you should be able to do a pull, regenerate your project files and move forwards.

Thanks for finding that,

Sean

**Comment by Herbie43** [comment]
Apolgies for delayed response, crunched at work. Appreciate your responsiveness. 
[FleetManagerLog.txt](https://github.com/spayne/GameLiftStarterPlugin/files/10528670/FleetManagerLog.txt)

Pulled latest, regenerated, launched game from VS2019, Dev Editor/Win65. Same crash. For extra measure afterwards I removed the space from the project directory.

**Comment by Herbie43** [comment]
Had to do one more adjustment. Inside of GameLiftStartSettings.cpp I needed to update the BOTO3Path for both user directory and version. With your changes and the BOTO3Path update, works like a charm. Thanks again for your efforts!
