### ISSUE TITLE
Error when opening FleetManager menu!

### ISSUE THREAD

**Issue by NotUsedAccount123** [spayne/GameLiftStarterPlugin#2]
Not sure what this is, or how to resolve it. 
It happens every time I try to open the Fleet Manger menu from within UE5 Platforms dropdown menu.
![image](https://user-images.githubusercontent.com/35529516/215712210-e1d75a24-c2b7-46cb-9552-13ddcce84c12.png)

**Comment by spayne** [comment]
Thanks for letting me know.  Do you have a call stack or some output from the console log?  This would help me figure out which shared pointer was going wrong.

**Comment by spayne** [comment]
Hi Zubey, 

I tried to reproduce this today - without logs - I'm just making guesses at this point.  What I did try is to disable the GameLiftStarter plugin to see if that would trigger that kind of crash.  But no, it prints " Fatal error: [File:E:\unreal folder with space\MyProject5\Plugins\FleetManager\Source\FleetManager\Public\IFleetManagerModule.h]" to the log and shuts down for that case.

Anyway if you can send me a log (or a portion of a log) that has a few more details this will help figure out what is going wrong.

**Comment by spayne** [comment]
I tried to reproduce another way - but still didn't get that issue.  So I'm going to close as I can't repro.

**Comment by spayne** [comment]
Hi Zubey,
Another developer found a SharedPointer issue and I believe that it was caused by the BOTO3 path not being set correctly in his project settings.  If you want to give it a try could pull the latest and try again (see https://github.com/spayne/GameLiftStarterPlugin/issues/4#issuecomment-1414568659) 
Thanks,
Sean
