### ISSUE TITLE
Won't compile under UE5.03

### ISSUE THREAD

**Issue by buzzdave** [spayne/GameLiftStarterPlugin#4]
First, thanks for making this plugin - I really needed something like this!
Attempting to build produced errors that were fixed:
![image](https://user-images.githubusercontent.com/1988667/216461088-88f8b152-4367-4a5c-8ffe-e6e63304b1ef.png)

Built fine after adding the getter, however on loading the project, I get the warning:
![image](https://user-images.githubusercontent.com/1988667/216461446-c941ef06-dc6b-430f-a1f2-a320ce93423d.png)

(As you can see I have spaces in the path, but this is the latest clone)
Running the FleetManager plugin then also crashes, with the stack:
Assertion failed: IsValid() [File:G:\PRIMARY\UE_5.0\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h] [Line: 1074]
UnrealEditor_FleetManagerModule!BridgedFleet::FFleet::CB() [C:\Users\Dave\Documents\Unreal Projects\MyGameLiftProject\Plugins\FleetManager\Source\FleetManager\Private\Fleet.cpp:225]
UnrealEditor_FleetManagerModule!TBaseSPMethodDelegateInstance<0,BridgedFleet::FFleet,1,void __cdecl(bool,FString const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\PRIMARY\UE_5.0\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UnrealEditor_FleetManagerModule!FFleetBridge::ConfigGetComplete() [C:\Users\Dave\Documents\Unreal Projects\MyGameLiftProject\Plugins\FleetManager\Source\FleetManager\Private\FleetBridge.cpp:132]
UnrealEditor_FleetManagerModule!TBaseRawMethodDelegateInstance<0,FFleetBridge,void __cdecl(TSharedPtr<IHttpRequest,1>,TSharedPtr<IHttpResponse,1>,bool),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\PRIMARY\UE_5.0\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:467]

**Comment by buzzdave** [comment]
Quick check - 
am I using the UE source build that I just got from Unreal?
am I using the game editor I installed as regular binaries? <--- probably this one.

**Comment by spayne** [comment]
Yeah I'm wondering what version you are running. e.g. 5.0 or 5.1 or git :)

Thanks for the detailed logs.  What is also interesting is that you have a shared pointer assert which someone else came up against but I couldn't repro.

This might be an Unreal 5.0 vs 5.1 issue where the path the BP_ThirdPersonCharacter has moved.  I'm testing against 5.1.

What you can do is right click on your uproject and select "Switch unreal Version" this should let you choose the source build you have

**Comment by spayne** [comment]
(I'll try on my side to see if I can confirm this 5.0 vs 5.1 difference)

**Comment by buzzdave** [comment]
Thanks.  I am now building the UE engine source I cloned today from Unreal.  I never even built it because I had been playing with other AWS plugins like GameKit.
I'll update and close once the engine is built and confirmed working...

**Comment by spayne** [comment]
It's a weird rule that you have to build from source to build dedicated servers - so you'd have to eventually :)

**Comment by buzzdave** [comment]
Yeah GameKit works fine as a plugin against the regular install.
But no dedicated servers there.
After cloning for 12GB and an hour of checking, updating and validating, I guess my brain was in post-compile mode

**Comment by buzzdave** [comment]
...and I crashed out of building UE5 sources. Boo
There's a known issue when building UE5, related to GitDependencies timing out while grabbing the .NET framework from MSFT.  Fix is discussed here:
https://forums.unrealengine.com/t/setup-bat-dependency-download-failing-for-windows-5-1-cant-find-anything-on-this-anywhere/719156/9

**Comment by spayne** [comment]
Let me know how it goes.  I believe the problem you are seeing is that you don't have correct boto3 settings.  So I'll put some code into handle that without crashing.

In the meantime, if you are working on it now, you can just check your settings.  Refer to https://github.com/spayne/GameLiftStarterPlugin#step-5---modify-your-project-to-support-gamelift

**Comment by buzzdave** [comment]
Will do, but I think my issue with building UE5 was that I ran out of disk space.  
Good grief, moving the UnrealEngine folder to another drive - almost 100GB!

**Comment by spayne** [comment]
I updated this project and it's dependency to do more validation of settings (to include boto3) which I think was going wrong.
To get the latest you'll need to pull both projects.  But may as well pull all 3 so everything is up to date. 

To update:
cd into your **project** Plugins folder at the same level as Source and then
cd into FleetManager and do a git pull
cd into GameLiftStarter and do a git pull
cd into GameLiftServerSDK and do a git pull.

This is somewhat optional because I think you can just fix it by setting the correct boto3 path.

**Comment by buzzdave** [comment]
I will leave this to you Sean.  My first-issue of building the project against 5.0.3 binaries was not building against a built-from-source codebase.  I built a fresh UE 5.1 engine from sources and a project with the plugins built fine.  
For anyone running into my other build problems - it was all due to not having enough disk space.  Built size disk space needed is over 100GB, so it can happen to anyone...

**Comment by spayne** [comment]
Ok cool thanks.  Since it is building against 5.1 now I'm going to mark it as closed.

Feel free to open up tickets though because it helps me and others.

I don't know if you want to hear this or not.... My opinion on disk space is that if you are doing Unreal C++ you need a 1TB SSD.  I used to have a T7 external SSD for a work laptop, but currently I'm using a 2TB internal on my PC.

**Comment by buzzdave** [comment]
> Ok cool thanks. Since it is building against 5.1 now I'm going to mark it as closed.
> 
> Feel free to open up tickets though because it helps me and others.
> 
> I don't know if you want to hear this or not.... My opinion on disk space is that if you are doing Unreal C++ you need a 1TB SSD. I used to have a T7 external SSD for a work laptop, but currently I'm using a 2TB internal on my PC.

Yep I moved the whole schmeel to my 1TB drive
