### ISSUE TITLE
Done building project "GameLift.vcxproj" -- FAILED How to fix?

### ISSUE THREAD

**Issue by Imloopdev** [spayne/GameLiftStarterPlugin#6]
When I use source build 5.1 to build for development editor win64 I get this error, Done building project "GameLift.vcxproj" -- FAILED.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "D:\Source\UnrealEngine\Engine\Build\BatchFiles\Build.bat -Target="GameLiftEditor Win64 Development -Project=\"C:\Users\ratho\Documents\Unreal Projects\GameLift\GameLift.uproject\"" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.

**Comment by spayne** [comment]
Hi Aryan,

Are you still having this issue?  If so, then the issue should stay open.
Is this the full build log?   I was expecting something > 1000 lines that might give some context to what is going on.

Thanks,
Sean
