### ISSUE TITLE
Fleet Manager empty

### ISSUE THREAD

**Issue by flanderone** [spayne/GameLiftStarterPlugin#7]
Hello,

I am at the beginning of the tutorial.

After installing python and boto3, I added the plugins to the project and built it using Visual Studio. When opening the project in Unreal, at first, indeed I got the boto3 path loading error log. After editing it in the Project Settings, the log went away and I was able to open Fleet Manager, however it is completely empty as it can be seen in the screenshot.

![FleetManager](https://github.com/spayne/GameLiftStarterPlugin/assets/26509121/cde715b1-4370-4d4d-99dd-9a41c600187a)

I do not see any other error logs. Would you know why this happens?

Thank you.

**Comment by spayne** [comment]
Thanks for posting the issue.  I can't really move forwards until I can get a bit more information / ie the logs.   I can post more detailed instructions later, but in the meantime I tried making a image to show you what I'm hoping you can do:
1. Open the fleet manager
2. select Output log in UE Editor
3. Copy the contents of output log to a text file
4. Attach the contents to this ticket.

See attached image.  Hopefully this will help troubleshoot.  Thanks.

![output_log](https://github.com/spayne/GameLiftStarterPlugin/assets/82259/7f601fbb-c02c-4d05-b40b-109307ca63c6)

**Comment by flanderone** [comment]
```


LogPython: Error: SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape (<string>, line 2)
LogPython: Error:   sys.path.insert(0,'c:\users\catal\appdata\local\programs\python\python310\lib\site-packages')
LogPython: Error:                                                                                               ^
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error: NameError: name 'fleet_bridge' is not defined
FleetManagerModule: Warning: got Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'fleet_bridge' is not defined
LogSlate: Took 0.005619 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Regular.ttf' (155K)
LogSlate: Took 0.004481 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Bold.ttf' (160K)
LogSlate: Took 0.004495 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Italic.ttf' (157K)
LogSlate: Took 0.000453 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/DroidSansMono.ttf' (77K)
LogViewport: Scene viewport resized to 1813x884, mode Windowed.
LogSlate: Took 0.000763 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Light.ttf' (167K)
LogStall: Startup...
LogStall: Startup complete.
LogLoad: (Engine Initialization) Total time: 38.85 seconds
LogLoad: (Engine Initialization) Total Blueprint compile time: 0.00 seconds
LogContentStreaming: Texture pool size now 1000 MB
LogViewport: Scene viewport resized to 1813x845, mode Windowed.
LogHttp: Warning: 00000687A353F500: invalid HTTP response code received. URL: http://localhost:8000/aws_backend/1/metadata?profile_name=GameliftAdmin&region_name=eu-central-1&prefix=testfleet&server_package_root=""&fleet_launch_path=""&project_root="C%3A%2FUsers%2Fcatal%2FDocuments%2FJOCUE%2F", HTTP code: 0, content length: 0, actual payload size: 0
LogHttp: Warning: 00000687A353F500: request failed, libcurl error: 7 (Couldn't connect to server)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 0 (  Trying 127.0.0.1:8000...)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 1 (  Trying ::1:8000...)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 2 (connect to 127.0.0.1 port 8000 failed: Connection refused)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 3 (connect to ::1 port 8000 failed: Connection refused)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 4 (Failed to connect to localhost port 8000 after 2239 ms: Connection refused)
LogHttp: Warning: 00000687A353F500: libcurl info message cache 5 (Closing connection 0)
FleetManagerModule: Warning: got invalid response: 0
FleetManagerModule: Error: Could not load backend metadata.  Check your Plugin Settings. e.g. Refer to https://github.com/spayne/GameLiftStarterPlugin#step-5---modify-your-project-to-support-gamelift
LogAssetRegistry: AssetRegistryGather time 0.3606s: AssetDataDiscovery 0.1404s, AssetDataGather 0.1464s, StoreResults 0.0737s.
LogCollectionManager: Fixed up redirectors for 0 collections in 0.000310 seconds (updated 0 objects)
```
```

![image](https://github.com/spayne/GameLiftStarterPlugin/assets/26509121/f79b4474-6ee2-4e32-bcf2-1edb34eb87ce)

Hello, thank you for your reply. Please have the logs above. It seems indeed that the issue is step 5, but I cannot tell which part as you can see in the screenshot I did adapt the boto3 path on my machine.

**Comment by spayne** [comment]
Thanks for the log information .  Hopefully this will help.  I think the following is interesting:

> LogPython: Error: SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \uXXXX escape (<string>, line 2)
> LogPython: Error:   sys.path.insert(0,'c:\users\catal\appdata\local\programs\python\python310\lib\site-packages')
> LogPython: Error:                                                                                               ^
> LogPython: Error: Traceback (most recent call last):
> LogPython: Error:   File "<string>", line 1, in <module>
> LogPython: Error: NameError: name 'fleet_bridge' is not defined

- What I see is that python is trying to decode \uXXXX and probably comes from the "c:\users".  i.e. it sees the \u in c:**\u**ser and it's expecting to find some unicode value from "ser".
- Anyway what I notice is that in my step 5 I'm using forward slashes.  
- So I think it's reasonable to guess that forward slashes would fix things for you.  e.g. use c:/users/catal/appdata/local/programs/python/python310/lib/site-packages instead.

Hope this helps.  Sorry for the inconvenience. I should probably do some more friendly error checking to see if the path and the string looks good to avoid this issue in the future.

**Comment by flanderone** [comment]
Thank you very much for the help, and sorry for bothering you for such a silly issue.

I can confirm that indeed after changing the backslash to forward slash the fleet manager displays correctly.

Thank you again!

**Comment by spayne** [comment]
Thanks for letting me know.  I appreciate you raising the ticket and getting the logs.  Based on this I think I should have those prompts be able to deal with both kinds of slashes.   ie using backslash paths should be supported.  

My goal for this plugin is that someone should be able to get up and running with GameLift in a single day - so clearing out sillyness like this should help with that goal.
